import sqlite3
import getpass
import psycopg

SUPABASE_HOST = "aws-1-eu-west-1.pooler.supabase.com"
SUPABASE_USER = "postgres.idojtsmrbkxbxafvwmck"
SUPABASE_DB = "postgres"
SUPABASE_PORT = 5432

SQL_CREATE = """
CREATE TABLE IF NOT EXISTS shipment (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tracking_number VARCHAR(50) NOT NULL UNIQUE,
    sender VARCHAR(100) NOT NULL,
    sender_address VARCHAR(200) NOT NULL,
    receiver VARCHAR(100) NOT NULL,
    receiver_address VARCHAR(200) NOT NULL,
    receiver_phone VARCHAR(50) NOT NULL,
    origin VARCHAR(100) NOT NULL,
    destination VARCHAR(100) NOT NULL,
    current_location VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL
);

CREATE TABLE IF NOT EXISTS tracking_event (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    shipment_id INTEGER NOT NULL,
    status VARCHAR(100) NOT NULL,
    location VARCHAR(100) NOT NULL,
    event_time TIMESTAMP NOT NULL,
    CONSTRAINT fk_tracking_shipment
        FOREIGN KEY (shipment_id)
        REFERENCES shipment(id)
);
"""


def main():
    password = getpass.getpass("Supabase database password: ")

    print("\nReading local SQLite database...")
    sqlite_db = sqlite3.connect("instance/courier.db")

    shipments = sqlite_db.execute(
        "SELECT id, tracking_number, sender, sender_address, "
        "receiver, receiver_address, receiver_phone, origin, "
        "destination, current_location, status "
        "FROM shipment ORDER BY id"
    ).fetchall()

    events = sqlite_db.execute(
        "SELECT id, shipment_id, status, location, event_time "
        "FROM tracking_event ORDER BY id"
    ).fetchall()

    sqlite_db.close()

    print(f"Found {len(shipments)} shipments.")
    print(f"Found {len(events)} tracking events.")

    print("\nConnecting to Supabase...")
    pg = psycopg.connect(
        host=SUPABASE_HOST,
        port=SUPABASE_PORT,
        dbname=SUPABASE_DB,
        user=SUPABASE_USER,
        password=password,
        sslmode="require"
    )

    try:
        with pg.cursor() as cur:
            print("Creating tables if they do not exist...")
            cur.execute(SQL_CREATE)

            existing_shipments = cur.execute(
                "SELECT COUNT(*) FROM shipment"
            ).fetchone()[0]

            existing_events = cur.execute(
                "SELECT COUNT(*) FROM tracking_event"
            ).fetchone()[0]

            if existing_shipments > 0 or existing_events > 0:
                raise RuntimeError(
                    f"Supabase already contains data "
                    f"({existing_shipments} shipments, "
                    f"{existing_events} tracking events). "
                    "Migration stopped to protect existing data."
                )

            print("Migrating shipments...")
            cur.executemany(
                """
                INSERT INTO shipment (
                    id, tracking_number, sender, sender_address,
                    receiver, receiver_address, receiver_phone,
                    origin, destination, current_location, status
                )
                VALUES (
                    %s, %s, %s, %s, %s, %s, %s,
                    %s, %s, %s, %s
                )
                """,
                shipments
            )

            print("Migrating tracking events...")
            cur.executemany(
                """
                INSERT INTO tracking_event (
                    id, shipment_id, status, location, event_time
                )
                VALUES (%s, %s, %s, %s, %s)
                """,
                events
            )

            print("Synchronizing PostgreSQL identity sequences...")

            cur.execute("""
                SELECT setval(
                    pg_get_serial_sequence('shipment', 'id'),
                    COALESCE((SELECT MAX(id) FROM shipment), 1),
                    true
                )
            """)

            cur.execute("""
                SELECT setval(
                    pg_get_serial_sequence('tracking_event', 'id'),
                    COALESCE((SELECT MAX(id) FROM tracking_event), 1),
                    true
                )
            """)

        pg.commit()

        with pg.cursor() as cur:
            shipment_count = cur.execute(
                "SELECT COUNT(*) FROM shipment"
            ).fetchone()[0]

            event_count = cur.execute(
                "SELECT COUNT(*) FROM tracking_event"
            ).fetchone()[0]

        print("\n================================")
        print("MIGRATION COMPLETED")
        print("================================")
        print(f"Supabase shipments: {shipment_count}")
        print(f"Supabase tracking events: {event_count}")

        if shipment_count == len(shipments) and event_count == len(events):
            print("VERIFICATION: SUCCESS")
        else:
            print("VERIFICATION: COUNT MISMATCH")

    except Exception:
        pg.rollback()
        print("\nMigration failed. No changes were committed.")
        raise

    finally:
        pg.close()


if __name__ == "__main__":
    main()